/datum/crafting_recipe/food/asspie // butts
	name = "Asspie"
	reqs = list(
		/datum/reagent/consumable/blackpepper = 1,
		/datum/reagent/consumable/salt = 1,
		/obj/item/food/pie/plain = 1,
		/obj/item/organ/butt = 1)
	result = /obj/item/food/pie/asspie
	subcategory = CAT_PIE
